import { Request, Response } from 'express';
import { v4 as uuidv4 } from 'uuid';
import { Op } from 'sequelize';
import User from '../models/User';
import SecretCode from '../models/SecretCode';
import AuditLog from '../models/AuditLog';
import logger from '../utils/logger';
import { generateCodeSchema, approveEmployeeSchema } from '../utils/validators';

export class AdminController {
  // Generate secret code for employee registration
  async generateSecretCode(req: Request, res: Response) {
    try {
      // Check if user is authenticated
      if (!req.user || !req.user.uid) {
        return res.status(401).json({
          success: false,
          error: { code: 'UNAUTHORIZED', message: 'User not authenticated' }
        });
      }

      const validation = generateCodeSchema.safeParse(req.body);
      if (!validation.success) {
        return res.status(400).json({
          success: false,
          error: { 
            code: 'VALIDATION_ERROR', 
            message: validation.error.issues[0].message
          }
        });
      }
      
      const { expiresInHours } = validation.data;
      const adminUid = req.user.uid; // Now guaranteed to be string
      const adminEmail = req.user.email;
      
      // Generate a secure random code
      const code = uuidv4().replace(/-/g, '').substring(0, 16);
      const expiresAt = new Date();
      expiresAt.setHours(expiresAt.getHours() + expiresInHours);
      
      // Create secret code using Sequelize
      const secretCode = await SecretCode.create({
        code,
        expiresAt,
        createdBy: adminUid, // Now definitely a string
        isUsed: false,
      });
      
      // Create audit log
      await AuditLog.create({
        eventType: 'SECRET_CODE_GENERATED',
        severity: 'INFO',
        firebaseUid: adminUid,
        email: adminEmail,
        details: { expiresInHours, code: secretCode.code },
      });
      
      logger.info(`Secret code generated by admin ${adminEmail}`, { code, expiresAt });
      
      res.status(201).json({
        success: true,
        data: {
          code: secretCode.code,
          expiresAt: secretCode.expiresAt,
          message: 'Secret code generated successfully'
        }
      });
      
    } catch (error) {
      logger.error('Error generating secret code', { error });
      res.status(500).json({
        success: false,
        error: { code: 'SERVER_ERROR', message: 'Failed to generate secret code' }
      });
    }
  }
  
  // Get all employees pending approval
  async getPendingEmployees(req: Request, res: Response) {
    try {
      const pendingEmployees = await User.findAll({
        where: {
          role: 'EMPLOYEE',
          status: 'email_verified'
        },
        attributes: ['id', 'firebaseUid', 'email', 'name', 'createdAt', 'secretCode'],
        order: [['createdAt', 'ASC']]
      });
      
      res.json({
        success: true,
        data: pendingEmployees
      });
      
    } catch (error) {
      logger.error('Error fetching pending employees', { error });
      res.status(500).json({
        success: false,
        error: { code: 'SERVER_ERROR', message: 'Failed to fetch pending employees' }
      });
    }
  }
  
  // Approve or reject employee registration
  async approveEmployee(req: Request, res: Response) {
    // Check if user is authenticated
    if (!req.user || !req.user.uid) {
      return res.status(401).json({
        success: false,
        error: { code: 'UNAUTHORIZED', message: 'User not authenticated' }
      });
    }

    const transaction = await User.sequelize!.transaction();
    
    try {
      const validation = approveEmployeeSchema.safeParse(req.body);
      if (!validation.success) {
        return res.status(400).json({
          success: false,
          error: { 
            code: 'VALIDATION_ERROR', 
            message: validation.error.issues[0].message
          }
        });
      }
      
      const { userId, approve, reason } = validation.data;
      const adminUid = req.user.uid; // Now guaranteed to be string
      const adminEmail = req.user.email;
      
      // Get the employee
      const employee = await User.findByPk(userId, { transaction });
      
      if (!employee) {
        await transaction.rollback();
        return res.status(404).json({
          success: false,
          error: { code: 'NOT_FOUND', message: 'Employee not found' }
        });
      }
      
      if (employee.role !== 'EMPLOYEE') {
        await transaction.rollback();
        return res.status(400).json({
          success: false,
          error: { code: 'INVALID_ROLE', message: 'User is not an employee' }
        });
      }
      
      if (employee.status !== 'email_verified') {
        await transaction.rollback();
        return res.status(400).json({
          success: false,
          error: { 
            code: 'INVALID_STATUS', 
            message: `Employee status is ${employee.status}, cannot approve/reject` 
          }
        });
      }
      
      if (approve) {
        // Approve employee
        await employee.update({
          status: 'active',
          approvedAt: new Date(),
          approvedBy: adminUid
        }, { transaction });
        
        // Mark the secret code as used if exists
        if (employee.secretCode) {
          await SecretCode.update(
            { isUsed: true, usedBy: employee.id, usedAt: new Date() },
            { 
              where: { code: employee.secretCode, isUsed: false },
              transaction 
            }
          );
        }
        
        // Create audit log
        await AuditLog.create({
          eventType: 'ADMIN_APPROVAL',
          severity: 'INFO',
          userId: employee.id,
          firebaseUid: adminUid,
          email: adminEmail,
          details: { approved: true, employeeEmail: employee.email }
        }, { transaction });
        
        await transaction.commit();
        
        logger.info(`Employee ${employee.email} approved by admin ${adminEmail}`);
        
        res.json({
          success: true,
          data: { message: 'Employee approved successfully' }
        });
        
      } else {
        // Reject employee
        await employee.update({
          status: 'rejected'
        }, { transaction });
        
        // Create audit log
        await AuditLog.create({
          eventType: 'ADMIN_REJECTION',
          severity: 'WARNING',
          userId: employee.id,
          firebaseUid: adminUid,
          email: adminEmail,
          details: { approved: false, reason, employeeEmail: employee.email }
        }, { transaction });
        
        await transaction.commit();
        
        logger.warn(`Employee ${employee.email} rejected by admin ${adminEmail}`, { reason });
        
        res.json({
          success: true,
          data: { message: 'Employee rejected successfully' }
        });
      }
      
    } catch (error) {
      await transaction.rollback();
      logger.error('Error approving/rejecting employee', { error });
      res.status(500).json({
        success: false,
        error: { code: 'SERVER_ERROR', message: 'Failed to process employee approval' }
      });
    }
  }
  
  // Get all users (admin only)
  async getAllUsers(req: Request, res: Response) {
    try {
      const users = await User.findAll({
        attributes: ['id', 'firebaseUid', 'email', 'name', 'role', 'status', 'createdAt', 'approvedAt', 'lastLogin'],
        order: [['createdAt', 'DESC']],
        limit: 100
      });
      
      res.json({
        success: true,
        data: users
      });
      
    } catch (error) {
      logger.error('Error fetching users', { error });
      res.status(500).json({
        success: false,
        error: { code: 'SERVER_ERROR', message: 'Failed to fetch users' }
      });
    }
  }
  
  // Get audit logs (admin only)
  async getAuditLogs(req: Request, res: Response) {
    try {
      const { limit = 100, offset = 0, eventType } = req.query;
      
      const where: any = {};
      if (eventType) {
        where.eventType = eventType;
      }
      
      const logs = await AuditLog.findAndCountAll({
        where,
        limit: parseInt(limit as string),
        offset: parseInt(offset as string),
        order: [['createdAt', 'DESC']],
        include: [
          {
            model: User,
            attributes: ['id', 'email', 'name'],
            required: false
          }
        ]
      });
      
      res.json({
        success: true,
        data: {
          logs: logs.rows,
          total: logs.count,
          limit: parseInt(limit as string),
          offset: parseInt(offset as string)
        }
      });
      
    } catch (error) {
      logger.error('Error fetching audit logs', { error });
      res.status(500).json({
        success: false,
        error: { code: 'SERVER_ERROR', message: 'Failed to fetch audit logs' }
      });
    }
  }
}